# Generated by Django 3.1.3 on 2020-11-24 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0002_auto_20201124_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='player_of_the_match',
            new_name='player_of_match',
        ),
        migrations.AddField(
            model_name='matches',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
