# Generated by Django 3.1.3 on 2020-11-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0004_auto_20201124_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='player_of_match',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
