# Generated by Django 3.1.3 on 2020-11-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0005_auto_20201124_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='non_striker',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='result',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='toss_decision',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='toss_winner',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='venue',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
