# Generated by Django 3.1.3 on 2020-11-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0006_auto_20201124_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='matchid',
            new_name='match_id',
        ),
    ]
